name: Augusto Decastro
favicon: null
layout_spectrum: 0.33889263961464167
typography_spectrum: 0.617379172006622
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.30756207392551005
  lightness: 0.14570811856538057
  saturation: 0.5747349706944078
  rhythmicContrast: 0.9410365053918213
purpose: []
