name: Augusto Decastro
favicon: null
layout_spectrum: 0.25146
typography_spectrum: 0.92939
title: Testing Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1ba2e6'
    - '#323232'
    - '#000000'
    - '#00ffff'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
