name: Augusto Decastro
favicon: null
layout_spectrum: 0.80506
typography_spectrum: 0.69547
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1c2510'
    - '#de3f21'
    - '#f7d166'
    - '#71f0df'
    - '#79a266'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
