name: Augusto Decastro
favicon: null
layout_spectrum: 0.00394
typography_spectrum: 0.69547
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#1ba2e6'
    - '#ffffff'
    - '#c4c4c4'
    - '#0f577d'
  brandStrength: 0.375
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
