name: Augusto Decastro
favicon: null
layout_spectrum: 0.84013
typography_spectrum: 0.87719
title: Testing Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#b1b597'
    - '#444851'
    - '#7b864c'
    - '#3b6f67'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
