name: Augusto Decastro
favicon: null
layout_spectrum: 0.24756
typography_spectrum: 0.69547
title: Testing Site
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f2022'
    - '#e4e4d8'
    - '#3e5d8c'
    - '#fd5049'
    - '#21b56e'
  brandStrength: 0.75
  lightness: 0.75
  saturation: 0.25
  rhythmicContrast: 0.25
purpose: []
